#!/usr/bin/env python3
"""
Interactive setup script for Map Dater environment configuration.

This script helps you create a .env file with your API keys and preferences.
"""

import os
from pathlib import Path
import shutil


def main():
    print("="*80)
    print("Map Dater - Environment Setup")
    print("="*80)
    print()

    project_root = Path(__file__).parent
    env_file = project_root / '.env'
    env_example = project_root / '.env.example'

    # Check if .env already exists
    if env_file.exists():
        print(f"⚠️  Found existing .env file at: {env_file}")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled. Your existing .env file was not modified.")
            return
        print()

    # Check if .env.example exists
    if not env_example.exists():
        print(f"❌ Error: .env.example not found at: {env_example}")
        print("This file should be in the project root directory.")
        return

    print("Let's configure your environment settings.")
    print()
    print("Required settings:")
    print("-" * 80)

    # Get API key
    print("\n1. Anthropic API Key (required for AI visual analysis)")
    print("   Get your key from: https://console.anthropic.com")
    api_key = input("   Enter your ANTHROPIC_API_KEY: ").strip()

    if not api_key:
        print("\n⚠️  No API key provided. AI features will not work.")
        print("You can add it later by editing the .env file.")
        api_key = ""

    print("\nOptional settings:")
    print("-" * 80)

    # Image upscaling
    print("\n2. Image upscaling for better OCR (recommended: 1.5)")
    print("   Higher values = better OCR but slower processing")
    print("   Options: 1.0 (no scaling), 1.5, 2.0")
    upscale = input("   PREPROCESSING_UPSCALE [1.5]: ").strip() or "1.5"

    # OCR confidence
    print("\n3. OCR confidence threshold (recommended: 0.3)")
    print("   Lower = more text detected, Higher = more accurate")
    print("   Range: 0.0 to 1.0")
    confidence = input("   OCR_CONFIDENCE_THRESHOLD [0.3]: ").strip() or "0.3"

    # Binarization
    print("\n4. Enable binarization for difficult maps?")
    print("   Converts image to black/white for better OCR on some maps")
    binarize = input("   PREPROCESSING_BINARIZATION (true/false) [false]: ").strip() or "false"

    # Verbose mode
    print("\n5. Enable verbose output?")
    verbose = input("   VERBOSE (true/false) [false]: ").strip() or "false"

    # Create .env file
    print("\nCreating .env file...")

    with open(env_file, 'w') as f:
        f.write("# Map Dater Environment Configuration\n")
        f.write("# Generated by setup_env.py\n")
        f.write("# See .env.example for all available options\n\n")

        f.write("# =============================================================================\n")
        f.write("# REQUIRED CONFIGURATION\n")
        f.write("# =============================================================================\n\n")

        f.write("# Anthropic API Key for AI visual analysis\n")
        f.write("# Get your key from: https://console.anthropic.com\n")
        if api_key:
            f.write(f"ANTHROPIC_API_KEY={api_key}\n")
        else:
            f.write("# ANTHROPIC_API_KEY=your_key_here\n")

        f.write("\n# =============================================================================\n")
        f.write("# OPTIONAL CONFIGURATION\n")
        f.write("# =============================================================================\n\n")

        f.write("# Image preprocessing\n")
        f.write(f"PREPROCESSING_UPSCALE={upscale}\n")
        f.write(f"PREPROCESSING_BINARIZATION={binarize}\n\n")

        f.write("# OCR settings\n")
        f.write(f"OCR_CONFIDENCE_THRESHOLD={confidence}\n\n")

        f.write("# Output settings\n")
        f.write(f"VERBOSE={verbose}\n\n")

        f.write("# For more options, see .env.example\n")

    print(f"\n✅ Created .env file at: {env_file}")
    print()
    print("Setup complete! You can now run:")
    print("  python examples/ai_analysis_demo.py path/to/map.jpg")
    print()
    print("To modify settings later, edit the .env file directly.")
    print("="*80)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
